name: Build Windows

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Pobranie kodu projektu
      uses: actions/checkout@v4

    - name: Instalacja Qt 6
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.3'
        cached: 'true'
        modules: 'qtwebengine qtmultimedia qtwebchannel qtpositioning'

    - name: Instalacja biblioteki FluidSynth przez vcpkg
      run: vcpkg install fluidsynth:x64-windows

    - name: Inicjalizacja środowiska MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Konfiguracja CMake (Release)
      run: cmake --fresh -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$env:Qt6_DIR" -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT\scripts\buildsystems\vcpkg.cmake"

    - name: Kompilacja projektu
      run: cmake --build build --config Release --parallel 4

    - name: Przygotowanie paczki dystrybucyjnej i windeployqt
      run: |
        New-Item -ItemType Directory -Force -Path dist
        Copy-Item build/898SimpleMidiPiano.exe dist/ -ErrorAction SilentlyContinue
        Copy-Item build/Release/898SimpleMidiPiano.exe dist/ -ErrorAction SilentlyContinue
        Copy-Item build/verovio.dll dist/ -ErrorAction SilentlyContinue
        
        # Uruchomienie windeployqt bez błędnej flagi
        & "$env:Qt6_DIR\bin\windeployqt.exe" --release --force dist/898SimpleMidiPiano.exe
        
        # Wrzucenie bibliotek DLL z vcpkg na końcu
        Copy-Item "$env:VCPKG_INSTALLATION_ROOT\installed\x64-windows\bin\*.dll" dist/

    - name: Archiwizacja i przygotowanie paczki
      uses: actions/upload-artifact@v4
      with:
        name: 898SimpleMidiPiano-Windows-Portable
        path: dist/
