name: Build Windows

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Pobranie kodu projektu
      uses: actions/checkout@v4

    - name: Instalacja Qt 6
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.3'
        cached: 'true'
        modules: 'qtwebengine'

    - name: Kompilacja Verovio
      run: |
        cmake -S verovio-develop/cmake -B verovio-develop/build -DCMAKE_BUILD_TYPE=Release
        cmake --build verovio-develop/build --config Release --parallel 4

    - name: Konfiguracja CMake (Release)
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$env:Qt6_DIR"

    - name: Kompilacja projektu
      run: cmake --build build --config Release --parallel 4

    - name: Deploy (windeployqt)
      run: |
        $windeployqt = Get-ChildItem -Path "$env:QT_PATH_VALUE" -Recurse -Filter "windeployqt.exe" | Select-Object -First 1
        if ($windeployqt) {
            Write-Host "Znaleziono: $($windeployqt.FullName)"
            & $windeployqt.FullName --release --force build/Release/898SimpleMidiPiano.exe
        } else {
            Write-Error "Nie znaleziono windeployqt.exe!"
            exit 1
        }

    - name: Archiwizacja i przygotowanie paczki
      uses: actions/upload-artifact@v4
      with:
        name: 898SimpleMidiPiano-Windows-Portable
        path: build/Release/
